### ISSUE TITLE
License violation with code used from objection

### ISSUE THREAD

**Issue by leonjza** [snooze6/FiOS#1]
Heya,

Neat GUI! Should make for some neat analysis in the future!

Unfortunately I could not help but notice a very clear license violation and copy and paste of almost all of the hooks in your agents directory [here](https://github.com/snooze6/FiOS/tree/master/src/gui/core/frida/agents) when compared to a project of mine called [objection](https://github.com/sensepost/objection).

A small example is simply the Android activity listing hook [here](https://github.com/snooze6/FiOS/blob/master/src/gui/core/frida/agents/hooking/list_activities.js) compared to the one in objection [here](https://github.com/sensepost/objection/blob/master/objection/hooks/android/hooking/list-activities.js). Apart from the fact that you have wrapped this in an export, everything else is the same.

Almost all of the hooks file names and comments in this project are also intact when compared to those in objection.

Please can you ensure that this projects license is appropriately updated, and attribution according to the "Attribution-NonCommercial-ShareAlike 4.0 International" license is correctly given everywhere that code was used from objection. For more information on how to proceed to fix this violation, please see https://creativecommons.org/licenses/by-nc-sa/4.0/

Thank you!

**Comment by snooze6** [comment]
First of all I feel sorry about the lack of recognition of your amazing tool ([Objection](https://github.com/sensepost/objection)) in the first commit of this tool.

I changed the license of the project to match the one used in objection. It can be found here [FiOS/license.txt](https://github.com/snooze6/FiOS/blob/master/license.txt)

As I´m not very familiar with the licenses I would like a confirmation that this is the correct way to proceed.

Thank you

**Comment by leonjza** [comment]
@snooze6 thank you for the update. I myself am not a legal expert so it might still be worth it to just double check. For now though, I think all should be good.

Thanks and good luck 👍
